-- G-LOKOO POS v0.8 - Credit & Part Payments
-- Run this once in Supabase SQL Editor after the existing G-LOKOO schema.

alter table public.sales
  add column if not exists amount_paid numeric(12,2) not null default 0,
  add column if not exists balance_due numeric(12,2) not null default 0,
  add column if not exists payment_status text not null default 'Paid'
    check (payment_status in ('Paid','Partially Paid','Unpaid')),
  add column if not exists due_date date;

create index if not exists sales_customer_balance_idx
  on public.sales(customer_id, payment_status, due_date);

create table if not exists public.sale_payments (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null,
  payment_reference text,
  paid_by uuid references auth.users(id) on delete set null,
  paid_at timestamptz not null default now()
);

create index if not exists sale_payments_sale_idx on public.sale_payments(sale_id);
create index if not exists sale_payments_customer_idx on public.sale_payments(customer_id, paid_at desc);

alter table public.sale_payments enable row level security;
drop policy if exists "Authenticated users can manage sale payments" on public.sale_payments;
create policy "Authenticated users can manage sale payments"
on public.sale_payments for all to authenticated using (true) with check (true);

-- Replace checkout RPC with payment-aware version.
drop function if exists public.complete_sale(text,bigint,uuid,numeric,numeric,numeric,text,text,jsonb);

create or replace function public.complete_sale(
  p_receipt_no text,
  p_customer_id bigint,
  p_cashier_id uuid,
  p_subtotal numeric,
  p_discount numeric,
  p_total numeric,
  p_payment_method text,
  p_payment_reference text,
  p_amount_paid numeric,
  p_payment_status text,
  p_due_date date,
  p_items jsonb
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_item jsonb;
  v_phone public.phone_units;
  v_product public.products;
  v_qty integer;
  v_product_id bigint;
  v_imei text;
  v_paid numeric := greatest(0, coalesce(p_amount_paid,0));
  v_total numeric := greatest(0, coalesce(p_total,0));
  v_balance numeric;
begin
  if v_paid > v_total then
    raise exception 'Amount paid cannot exceed sale total';
  end if;

  if p_payment_status in ('Credit','Unpaid') then
    v_paid := 0;
  end if;

  v_balance := greatest(v_total - v_paid, 0);

  if v_balance > 0 and p_customer_id is null then
    raise exception 'A customer is required for credit or part payment sales';
  end if;

  insert into public.sales (
    receipt_no, customer_id, cashier_id, subtotal, discount, total,
    payment_method, payment_reference, amount_paid, balance_due,
    payment_status, due_date
  )
  values (
    p_receipt_no, p_customer_id, p_cashier_id, p_subtotal, p_discount, v_total,
    p_payment_method, nullif(trim(coalesce(p_payment_reference, '')), ''),
    v_paid, v_balance,
    case when v_balance = 0 then 'Paid' when v_paid > 0 then 'Partially Paid' else 'Unpaid' end,
    p_due_date
  )
  returning * into v_sale;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((v_item->>'quantity')::integer, 1));
    v_product_id := nullif(v_item->>'product_id', '')::bigint;
    v_imei := nullif(trim(v_item->>'imei'), '');

    if v_imei is not null then
      if v_qty <> 1 then raise exception 'A phone IMEI can only be sold as quantity 1'; end if;
      select * into v_phone from public.phone_units
      where imei_1 = v_imei or imei_2 = v_imei for update;
      if not found then raise exception 'IMEI % was not found', v_imei; end if;
      if v_phone.status <> 'In Stock' then raise exception 'IMEI % is already %', v_imei, v_phone.status; end if;

      insert into public.sale_items(sale_id,product_id,product_name,imei,quantity,unit_price,line_total)
      values(v_sale.id,v_phone.product_id,concat_ws(' ',v_phone.brand,v_phone.model),v_imei,1,v_phone.selling_price,v_phone.selling_price);

      update public.phone_units set status='Sold',sold_at=now(),sale_id=v_sale.id where id=v_phone.id;
    else
      if v_product_id is null then raise exception 'A sale item must have a product_id or IMEI'; end if;
      select * into v_product from public.products where id=v_product_id for update;
      if not found then raise exception 'Product % was not found',v_product_id; end if;
      if v_product.stock < v_qty then raise exception 'Not enough stock for %. Available: %, requested: %',v_product.name,v_product.stock,v_qty; end if;

      insert into public.sale_items(sale_id,product_id,product_name,imei,quantity,unit_price,line_total)
      values(v_sale.id,v_product.id,v_product.name,null,v_qty,v_product.price,v_product.price*v_qty);
      update public.products set stock=stock-v_qty where id=v_product.id;
    end if;
  end loop;

  if v_paid > 0 then
    insert into public.sale_payments(sale_id,customer_id,amount,payment_method,payment_reference,paid_by)
    values(v_sale.id,p_customer_id,v_paid,p_payment_method,nullif(trim(coalesce(p_payment_reference,'')),''),p_cashier_id);
  end if;

  return v_sale;
end;
$$;

grant execute on function public.complete_sale(text,bigint,uuid,numeric,numeric,numeric,text,text,numeric,text,date,jsonb) to authenticated;

-- Useful view for customer outstanding balances.
create or replace view public.customer_balances as
select
  c.id as customer_id,
  c.name,
  c.phone,
  coalesce(sum(case when s.balance_due > 0 then s.balance_due else 0 end),0)::numeric(12,2) as balance_due
from public.customers c
left join public.sales s on s.customer_id = c.id
group by c.id, c.name, c.phone;


-- Record a later payment against an outstanding customer sale.
create or replace function public.record_customer_payment(
  p_sale_id bigint,
  p_amount numeric,
  p_payment_method text,
  p_payment_reference text default null,
  p_paid_by uuid default null
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_amount numeric := greatest(0, coalesce(p_amount,0));
  v_new_paid numeric;
  v_new_balance numeric;
begin
  if v_amount <= 0 then raise exception 'Payment amount must be greater than zero'; end if;
  select * into v_sale from public.sales where id=p_sale_id for update;
  if not found then raise exception 'Sale % was not found', p_sale_id; end if;
  if v_sale.customer_id is null then raise exception 'This sale has no customer account'; end if;
  if v_sale.balance_due <= 0 then raise exception 'This sale is already fully paid'; end if;
  if v_amount > v_sale.balance_due then raise exception 'Payment cannot exceed the outstanding balance of %', v_sale.balance_due; end if;

  v_new_paid := v_sale.amount_paid + v_amount;
  v_new_balance := greatest(v_sale.total - v_new_paid,0);

  update public.sales set
    amount_paid=v_new_paid,
    balance_due=v_new_balance,
    payment_status=case when v_new_balance=0 then 'Paid' else 'Partially Paid' end
  where id=v_sale.id
  returning * into v_sale;

  insert into public.sale_payments(sale_id,customer_id,amount,payment_method,payment_reference,paid_by)
  values(v_sale.id,v_sale.customer_id,v_amount,nullif(trim(coalesce(p_payment_method,'')),''),nullif(trim(coalesce(p_payment_reference,'')),''),p_paid_by);

  return v_sale;
end;
$$;

grant execute on function public.record_customer_payment(bigint,numeric,text,text,uuid) to authenticated;
