-- G-LOKOO POS v2.18.0 — Inventory Control / Phone Movement History
-- Run ONCE in Supabase SQL Editor after v2.17.0 inventory-adjustments-schema.sql.

create table if not exists public.phone_stock_movements (
  id bigint generated by default as identity primary key,
  phone_unit_id bigint not null references public.phone_units(id) on delete cascade,
  from_status text,
  to_status text not null,
  reason text not null,
  note text,
  sale_id bigint references public.sales(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists phone_stock_movements_phone_created_idx
  on public.phone_stock_movements(phone_unit_id, created_at desc);

alter table public.phone_stock_movements enable row level security;
drop policy if exists "authenticated phone stock movements read" on public.phone_stock_movements;
create policy "authenticated phone stock movements read"
  on public.phone_stock_movements for select to authenticated using (true);

grant select on public.phone_stock_movements to authenticated;

create or replace function public.log_phone_stock_movement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reason text;
  v_from text;
  v_to text;
begin
  if tg_op = 'INSERT' then
    v_from := null;
    v_to := coalesce(new.status, 'In Stock');
    v_reason := 'Phone added to inventory';
    insert into public.phone_stock_movements(phone_unit_id,from_status,to_status,reason,sale_id,created_by)
    values(new.id,v_from,v_to,v_reason,new.sale_id,auth.uid());
    return new;
  end if;

  if tg_op = 'UPDATE' and coalesce(old.status,'') is distinct from coalesce(new.status,'') then
    v_from := old.status;
    v_to := coalesce(new.status,'');
    v_reason := case
      when v_to='Sold' then 'Phone sold'
      when v_to='Returned' then 'Phone returned'
      when v_to='Reserved' then 'Phone reserved'
      when v_to='In Stock' and v_from='Sold' then 'Phone sale reversed'
      else 'Phone status changed'
    end;
    insert into public.phone_stock_movements(phone_unit_id,from_status,to_status,reason,sale_id,created_by)
    values(new.id,v_from,v_to,v_reason,new.sale_id,auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_log_phone_stock_movement on public.phone_units;
create trigger trg_log_phone_stock_movement
after insert or update of status on public.phone_units
for each row execute function public.log_phone_stock_movement();

-- Helpful read-only view for inventory control.
create or replace view public.inventory_movement_summary as
select
  sm.id,
  sm.product_id,
  p.name as product_name,
  p.category,
  sm.change_qty,
  sm.stock_before,
  sm.stock_after,
  sm.reason,
  sm.note,
  sm.created_by,
  sm.created_at
from public.stock_movements sm
join public.products p on p.id=sm.product_id;

grant select on public.inventory_movement_summary to authenticated;
