-- G-LOKOO POS v2.17.0 — Advanced Inventory / Stock Adjustments
-- Run ONCE in Supabase SQL Editor.
-- This is an incremental migration; do not rerun the original full schema.

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  change_qty integer not null check (change_qty <> 0),
  stock_before integer not null,
  stock_after integer not null check (stock_after >= 0),
  reason text not null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists stock_movements_product_created_idx
  on public.stock_movements(product_id, created_at desc);

alter table public.stock_movements enable row level security;

drop policy if exists "authenticated stock movements read" on public.stock_movements;
create policy "authenticated stock movements read"
  on public.stock_movements for select to authenticated using (true);

create or replace function public.adjust_product_stock(
  p_product_id bigint,
  p_change_qty integer,
  p_reason text,
  p_note text default null,
  p_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_before integer;
  v_after integer;
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'You must be signed in to adjust stock.';
  end if;

  if p_user_id is not null and p_user_id <> v_user then
    raise exception 'Invalid stock adjustment user.';
  end if;

  select role into v_role
  from public.profiles
  where id = v_user;

  if coalesce(v_role, '') not in ('owner','admin','inventory') then
    raise exception 'Only Owner, Admin or Inventory staff can adjust stock.';
  end if;

  if p_change_qty is null or p_change_qty = 0 then
    raise exception 'Stock adjustment quantity cannot be zero.';
  end if;

  if coalesce(trim(p_reason), '') = '' then
    raise exception 'A stock adjustment reason is required.';
  end if;

  select stock into v_before
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'Product not found.';
  end if;

  v_after := v_before + p_change_qty;
  if v_after < 0 then
    raise exception 'Stock cannot go below zero. Current stock: %.', v_before;
  end if;

  update public.products
  set stock = v_after
  where id = p_product_id;

  insert into public.stock_movements(
    product_id, change_qty, stock_before, stock_after, reason, note, created_by
  ) values (
    p_product_id, p_change_qty, v_before, v_after,
    trim(p_reason), nullif(trim(p_note), ''), v_user
  );

  return jsonb_build_object(
    'product_id', p_product_id,
    'stock_before', v_before,
    'stock_after', v_after,
    'change_qty', p_change_qty
  );
end;
$$;

revoke all on function public.adjust_product_stock(bigint, integer, text, text, uuid) from public;
grant execute on function public.adjust_product_stock(bigint, integer, text, text, uuid) to authenticated;
