-- G-LOKOO POS v0.5 - Purchases / Stock In
-- Run this file AFTER your existing G-LOKOO schema.

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  purchase_no text unique not null,
  supplier text,
  invoice_no text,
  purchase_date date not null default current_date,
  received_by uuid references auth.users(id) on delete set null,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  item_type text not null check (item_type in ('accessory','phone')),
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_cost numeric(12,2) not null default 0,
  imei_1 text,
  imei_2 text,
  brand text,
  model text,
  storage text,
  ram text,
  color text,
  condition text,
  selling_price numeric(12,2),
  warranty text,
  created_at timestamptz not null default now()
);

create index if not exists purchases_date_idx on public.purchases(purchase_date desc);
create index if not exists purchase_items_purchase_idx on public.purchase_items(purchase_id);

alter table public.purchases enable row level security;
alter table public.purchase_items enable row level security;

drop policy if exists "Authenticated users can manage purchases" on public.purchases;
create policy "Authenticated users can manage purchases"
on public.purchases for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can manage purchase items" on public.purchase_items;
create policy "Authenticated users can manage purchase items"
on public.purchase_items for all to authenticated using (true) with check (true);

create or replace function public.receive_purchase(
  p_supplier text,
  p_invoice_no text,
  p_purchase_date date,
  p_received_by uuid,
  p_total numeric,
  p_items jsonb
)
returns public.purchases
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.purchases;
  v_item jsonb;
  v_type text;
  v_product_id bigint;
  v_product public.products;
  v_qty integer;
  v_purchase_no text;
  v_phone_id bigint;
begin
  v_purchase_no := 'PUR-' || to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');

  insert into public.purchases(
    purchase_no, supplier, invoice_no, purchase_date, received_by, total
  ) values (
    v_purchase_no,
    nullif(trim(coalesce(p_supplier,'')),''),
    nullif(trim(coalesce(p_invoice_no,'')),''),
    coalesce(p_purchase_date,current_date),
    p_received_by,
    coalesce(p_total,0)
  ) returning * into v_purchase;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_type := coalesce(v_item->>'type','');

    if v_type = 'accessory' then
      v_product_id := nullif(v_item->>'product_id','')::bigint;
      v_qty := greatest(1,coalesce((v_item->>'quantity')::integer,1));

      select * into v_product
      from public.products
      where id = v_product_id
      for update;

      if not found then
        raise exception 'Product % was not found', v_product_id;
      end if;

      insert into public.purchase_items(
        purchase_id,item_type,product_id,product_name,quantity,unit_cost
      ) values (
        v_purchase.id,'accessory',v_product.id,v_product.name,v_qty,
        coalesce((v_item->>'unit_cost')::numeric,0)
      );

      update public.products
      set stock = stock + v_qty,
          cost = coalesce((v_item->>'unit_cost')::numeric,cost)
      where id = v_product.id;

    elsif v_type = 'phone' then
      if nullif(trim(v_item->>'imei_1'),'') is null then
        raise exception 'Phone IMEI 1 is required';
      end if;
      if nullif(trim(v_item->>'brand'),'') is null or nullif(trim(v_item->>'model'),'') is null then
        raise exception 'Phone brand and model are required';
      end if;

      insert into public.phone_units(
        brand,model,storage,ram,color,condition,imei_1,imei_2,
        cost,selling_price,supplier,purchase_date,warranty,status
      ) values (
        trim(v_item->>'brand'),trim(v_item->>'model'),
        nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),
        nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),
        trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),
        coalesce((v_item->>'cost')::numeric,0),coalesce((v_item->>'selling_price')::numeric,0),
        nullif(trim(coalesce(p_supplier,'')),''),coalesce(p_purchase_date,current_date),
        nullif(trim(v_item->>'warranty'),''),'In Stock'
      ) returning id into v_phone_id;

      insert into public.purchase_items(
        purchase_id,item_type,product_name,quantity,unit_cost,
        imei_1,imei_2,brand,model,storage,ram,color,condition,selling_price,warranty
      ) values (
        v_purchase.id,'phone',
        trim(v_item->>'brand') || ' ' || trim(v_item->>'model'),1,
        coalesce((v_item->>'cost')::numeric,0),
        trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),
        trim(v_item->>'brand'),trim(v_item->>'model'),
        nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),
        nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),
        coalesce((v_item->>'selling_price')::numeric,0),nullif(trim(v_item->>'warranty'),'')
      );
    else
      raise exception 'Unknown purchase item type: %', v_type;
    end if;
  end loop;

  return v_purchase;
end;
$$;

grant execute on function public.receive_purchase(text,text,date,uuid,numeric,jsonb) to authenticated;
