-- G-LOKOO POS v1.5 - Sales Returns & Refunds
-- Run after the existing G-LOKOO migrations. Safe to run more than once.

create table if not exists public.sale_returns (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete restrict,
  refund_total numeric(12,2) not null default 0,
  refund_method text not null default 'Cash',
  refund_reference text,
  reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_return_items (
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.sale_returns(id) on delete cascade,
  sale_item_id bigint not null references public.sale_items(id) on delete restrict,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  imei text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists sale_returns_sale_id_idx on public.sale_returns(sale_id);
create index if not exists sale_returns_created_at_idx on public.sale_returns(created_at desc);
create index if not exists sale_return_items_return_id_idx on public.sale_return_items(return_id);
create index if not exists sale_return_items_sale_item_id_idx on public.sale_return_items(sale_item_id);

alter table public.sale_returns enable row level security;
alter table public.sale_return_items enable row level security;

drop policy if exists "management can read sale returns" on public.sale_returns;
create policy "management can read sale returns" on public.sale_returns
for select to authenticated using (public.is_management());

drop policy if exists "management can insert sale returns" on public.sale_returns;
create policy "management can insert sale returns" on public.sale_returns
for insert to authenticated with check (public.is_management());

drop policy if exists "management can read sale return items" on public.sale_return_items;
create policy "management can read sale return items" on public.sale_return_items
for select to authenticated using (public.is_management());

drop policy if exists "management can insert sale return items" on public.sale_return_items;
create policy "management can insert sale return items" on public.sale_return_items
for insert to authenticated with check (public.is_management());

create or replace function public.process_sale_return(
  p_sale_id bigint,
  p_items jsonb,
  p_refund_method text default 'Cash',
  p_refund_reference text default null,
  p_reason text default null,
  p_created_by uuid default auth.uid()
)
returns public.sale_returns
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_return public.sale_returns;
  v_item jsonb;
  v_sale_item public.sale_items;
  v_return_qty integer;
  v_already_returned integer;
  v_available integer;
  v_refund numeric(12,2) := 0;
  v_total numeric(12,2);
  v_paid numeric(12,2);
  v_balance numeric(12,2);
  v_status text;
  v_phone public.phone_units;
begin
  if not public.is_management() then
    raise exception 'Only Owner or Admin can process sales returns';
  end if;

  select * into v_sale from public.sales where id = p_sale_id for update;
  if not found then raise exception 'Sale % was not found', p_sale_id; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Select at least one item to return';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select * into v_sale_item from public.sale_items where id = (v_item->>'sale_item_id')::bigint and sale_id = p_sale_id for update;
    if not found then raise exception 'Sale item was not found on this sale'; end if;

    v_return_qty := greatest(1, coalesce((v_item->>'quantity')::integer, 1));
    select coalesce(sum(quantity),0) into v_already_returned from public.sale_return_items where sale_item_id = v_sale_item.id;
    v_available := v_sale_item.quantity - v_already_returned;
    if v_return_qty > v_available then
      raise exception 'Only % unit(s) of % can still be returned', v_available, v_sale_item.product_name;
    end if;
    if v_sale_item.imei is not null and v_return_qty <> 1 then
      raise exception 'A phone IMEI can only be returned as quantity 1';
    end if;
    v_refund := v_refund + (v_return_qty * v_sale_item.unit_price);
  end loop;

  if v_refund <= 0 then raise exception 'Return amount must be greater than zero'; end if;
  if v_refund > coalesce(v_sale.amount_paid,0) then
    raise exception 'Refund % cannot exceed the amount already paid (%).', v_refund, coalesce(v_sale.amount_paid,0);
  end if;

  insert into public.sale_returns (sale_id, refund_total, refund_method, refund_reference, reason, created_by)
  values (p_sale_id, v_refund, coalesce(nullif(trim(p_refund_method),''),'Cash'), nullif(trim(coalesce(p_refund_reference,'')),''), nullif(trim(coalesce(p_reason,'')),''), p_created_by)
  returning * into v_return;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select * into v_sale_item from public.sale_items where id = (v_item->>'sale_item_id')::bigint and sale_id = p_sale_id for update;
    v_return_qty := greatest(1, coalesce((v_item->>'quantity')::integer, 1));

    insert into public.sale_return_items (return_id, sale_item_id, product_id, product_name, imei, quantity, unit_price, line_total)
    values (v_return.id, v_sale_item.id, v_sale_item.product_id, v_sale_item.product_name, v_sale_item.imei, v_return_qty, v_sale_item.unit_price, v_return_qty * v_sale_item.unit_price);

    if v_sale_item.imei is not null then
      select * into v_phone from public.phone_units where (imei_1 = v_sale_item.imei or imei_2 = v_sale_item.imei) for update;
      if not found then raise exception 'Phone IMEI % was not found in inventory', v_sale_item.imei; end if;
      if v_phone.sale_id is distinct from p_sale_id or v_phone.status <> 'Sold' then
        raise exception 'Phone IMEI % is not currently sold on this sale', v_sale_item.imei;
      end if;
      update public.phone_units set status='Returned' where id=v_phone.id;
    elsif v_sale_item.product_id is not null then
      update public.products set stock=stock+v_return_qty where id=v_sale_item.product_id;
    end if;
  end loop;

  v_total := greatest(coalesce(v_sale.total,0) - v_refund, 0);
  v_paid := greatest(coalesce(v_sale.amount_paid,0) - v_refund, 0);
  v_balance := greatest(v_total - v_paid, 0);
  v_status := case when v_balance <= 0 then 'Paid' else case when v_paid > 0 then 'Part Payment' else 'Credit' end end;

  update public.sales
  set subtotal=greatest(coalesce(subtotal,0)-v_refund,0),
      total=v_total,
      amount_paid=v_paid,
      balance_due=v_balance,
      payment_status=v_status
  where id=p_sale_id;

  return v_return;
end;
$$;

grant execute on function public.process_sale_return(bigint,jsonb,text,text,text,uuid) to authenticated;
