-- G-LOKOO PHONES AND ACCESSORIES POS
-- Run this script in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'cashier' check (role in ('owner','admin','cashier','inventory','technician')),
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Accessories',
  sku text unique,
  barcode text unique,
  brand text,
  model text,
  color text,
  storage text,
  ram text,
  condition text default 'New',
  imei_1 text unique,
  imei_2 text unique,
  price numeric(12,2) not null default 0,
  cost numeric(12,2) not null default 0,
  stock integer not null default 0,
  warranty text,
  supplier text,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  receipt_no text unique not null,
  customer_id bigint references public.customers(id) on delete set null,
  cashier_id uuid references auth.users(id) on delete set null,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text not null default 'Cash',
  payment_reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  imei text,
  quantity integer not null default 1,
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  category text,
  amount numeric(12,2) not null default 0,
  expense_date date not null default current_date,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.repairs (
  id bigint generated by default as identity primary key,
  job_no text unique not null,
  customer_id bigint references public.customers(id) on delete set null,
  device text not null,
  imei text,
  fault text,
  technician_id uuid references auth.users(id) on delete set null,
  status text not null default 'Received',
  repair_cost numeric(12,2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create or replace function public.decrement_product_stock(p_product_id bigint, p_quantity integer)
returns void
language plpgsql
security invoker
as $$
begin
  update public.products
  set stock = greatest(stock - p_quantity, 0)
  where id = p_product_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.expenses enable row level security;
alter table public.repairs enable row level security;

-- Starter policies: authenticated POS users can use the operational tables.
-- Tighten these by role before production if you need cashier restrictions.
create policy "authenticated profiles read" on public.profiles for select to authenticated using (true);
create policy "authenticated products all" on public.products for all to authenticated using (true) with check (true);
create policy "authenticated customers all" on public.customers for all to authenticated using (true) with check (true);
create policy "authenticated sales all" on public.sales for all to authenticated using (true) with check (true);
create policy "authenticated sale items all" on public.sale_items for all to authenticated using (true) with check (true);
create policy "authenticated expenses all" on public.expenses for all to authenticated using (true) with check (true);
create policy "authenticated repairs all" on public.repairs for all to authenticated using (true) with check (true);

-- Optional starter profile trigger: create a profile whenever a user registers.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''), 'cashier')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- IMPORTANT: Create the first owner/admin user from Supabase Dashboard > Authentication > Users.
-- Then change that user's profile role to 'owner' with:
-- update public.profiles set role='owner' where id='YOUR-USER-UUID';

-- ============================================================
-- G-LOKOO v0.3: Individual Phone Units / IMEI Inventory
-- ============================================================

create table if not exists public.phone_units (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  brand text not null,
  model text not null,
  storage text,
  ram text,
  color text,
  condition text not null default 'New' check (condition in ('New','Used','Refurbished')),
  imei_1 text not null unique,
  imei_2 text unique,
  cost numeric(12,2) not null default 0,
  selling_price numeric(12,2) not null default 0,
  supplier text,
  purchase_date date,
  warranty text,
  status text not null default 'In Stock' check (status in ('In Stock','Reserved','Sold','Returned')),
  sold_at timestamptz,
  sale_id bigint references public.sales(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists phone_units_imei_1_idx on public.phone_units (imei_1);
create index if not exists phone_units_imei_2_idx on public.phone_units (imei_2);
create index if not exists phone_units_status_idx on public.phone_units (status);

alter table public.phone_units enable row level security;

drop policy if exists "Authenticated users can view phone units" on public.phone_units;
create policy "Authenticated users can view phone units"
on public.phone_units for select to authenticated using (true);

drop policy if exists "Authenticated users can manage phone units" on public.phone_units;
create policy "Authenticated users can manage phone units"
on public.phone_units for all to authenticated
using (true) with check (true);

create or replace function public.find_phone_by_imei(p_imei text)
returns setof public.phone_units
language sql
security definer
set search_path = public
as $$
  select *
  from public.phone_units
  where imei_1 = trim(p_imei)
     or imei_2 = trim(p_imei)
  limit 1;
$$;

grant execute on function public.find_phone_by_imei(text) to authenticated;

create or replace function public.sell_phone_unit(
  p_imei text,
  p_sale_id bigint
)
returns public.phone_units
language plpgsql
security definer
set search_path = public
as $$
declare
  v_unit public.phone_units;
begin
  select *
    into v_unit
  from public.phone_units
  where imei_1 = trim(p_imei)
     or imei_2 = trim(p_imei)
  for update;

  if not found then
    raise exception 'IMEI % was not found', p_imei;
  end if;

  if v_unit.status <> 'In Stock' then
    raise exception 'IMEI % is already %', p_imei, v_unit.status;
  end if;

  update public.phone_units
  set status = 'Sold', sold_at = now(), sale_id = p_sale_id
  where id = v_unit.id
  returning * into v_unit;

  return v_unit;
end;
$$;

grant execute on function public.sell_phone_unit(text,bigint) to authenticated;

-- ============================================================
-- G-LOKOO POS v0.4
-- ATOMIC POS CHECKOUT WITH PHONE IMEI SUPPORT
-- ============================================================

create or replace function public.complete_sale(
  p_receipt_no text,
  p_customer_id bigint,
  p_cashier_id uuid,
  p_subtotal numeric,
  p_discount numeric,
  p_total numeric,
  p_payment_method text,
  p_payment_reference text,
  p_items jsonb
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_item jsonb;
  v_phone public.phone_units;
  v_product public.products;
  v_qty integer;
  v_product_id bigint;
  v_imei text;
begin
  -- Create the sale first; all following work is part of the same transaction.
  insert into public.sales (
    receipt_no, customer_id, cashier_id, subtotal, discount, total,
    payment_method, payment_reference
  )
  values (
    p_receipt_no, p_customer_id, p_cashier_id, p_subtotal, p_discount, p_total,
    p_payment_method, nullif(trim(coalesce(p_payment_reference, '')), '')
  )
  returning * into v_sale;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((v_item->>'quantity')::integer, 1));
    v_product_id := nullif(v_item->>'product_id', '')::bigint;
    v_imei := nullif(trim(v_item->>'imei'), '');

    -- A phone unit is always sold as exactly one physical device.
    if v_imei is not null then
      if v_qty <> 1 then
        raise exception 'A phone IMEI can only be sold as quantity 1';
      end if;

      select *
      into v_phone
      from public.phone_units
      where imei_1 = v_imei
         or imei_2 = v_imei
      for update;

      if not found then
        raise exception 'IMEI % was not found', v_imei;
      end if;

      if v_phone.status <> 'In Stock' then
        raise exception 'IMEI % is already %', v_imei, v_phone.status;
      end if;

      insert into public.sale_items (
        sale_id, product_id, product_name, imei, quantity, unit_price, line_total
      )
      values (
        v_sale.id,
        v_phone.product_id,
        concat_ws(' ', v_phone.brand, v_phone.model),
        v_imei,
        1,
        v_phone.selling_price,
        v_phone.selling_price
      );

      update public.phone_units
      set status = 'Sold',
          sold_at = now(),
          sale_id = v_sale.id
      where id = v_phone.id;

    else
      -- Normal stock item / accessory.
      if v_product_id is null then
        raise exception 'A sale item must have a product_id or IMEI';
      end if;

      select *
      into v_product
      from public.products
      where id = v_product_id
      for update;

      if not found then
        raise exception 'Product % was not found', v_product_id;
      end if;

      if v_product.stock < v_qty then
        raise exception 'Not enough stock for %. Available: %, requested: %',
          v_product.name, v_product.stock, v_qty;
      end if;

      insert into public.sale_items (
        sale_id, product_id, product_name, imei, quantity, unit_price, line_total
      )
      values (
        v_sale.id,
        v_product.id,
        v_product.name,
        null,
        v_qty,
        v_product.price,
        v_product.price * v_qty
      );

      update public.products
      set stock = stock - v_qty
      where id = v_product.id;
    end if;
  end loop;

  return v_sale;
end;
$$;

grant execute on function public.complete_sale(
  text, bigint, uuid, numeric, numeric, numeric, text, text, jsonb
) to authenticated;
