-- G-LOKOO POS v2.4 - Supplier Management
-- Run once in Supabase SQL Editor after the existing schemas.

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text,
  email text,
  address text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.purchases
  add column if not exists supplier_id bigint references public.suppliers(id) on delete set null;

create index if not exists purchases_supplier_idx on public.purchases(supplier_id);

create table if not exists public.supplier_payments (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'Cash',
  reference text,
  paid_by uuid references auth.users(id) on delete set null,
  paid_at timestamptz not null default now()
);

create index if not exists supplier_payments_supplier_idx on public.supplier_payments(supplier_id, paid_at desc);

alter table public.suppliers enable row level security;
alter table public.supplier_payments enable row level security;

drop policy if exists "Authenticated users can manage suppliers" on public.suppliers;
create policy "Authenticated users can manage suppliers"
on public.suppliers for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can manage supplier payments" on public.supplier_payments;
create policy "Authenticated users can manage supplier payments"
on public.supplier_payments for all to authenticated using (true) with check (true);

-- View combines purchases with supplier payments.
create or replace view public.supplier_balances as
select
  s.id,
  s.name,
  s.phone,
  s.email,
  s.address,
  s.notes,
  s.active,
  coalesce(p.purchase_total,0) as purchase_total,
  coalesce(pay.paid_total,0) as paid_total,
  greatest(coalesce(p.purchase_total,0)-coalesce(pay.paid_total,0),0) as balance,
  s.created_at
from public.suppliers s
left join (
  select supplier_id, sum(total) as purchase_total
  from public.purchases
  where supplier_id is not null
  group by supplier_id
) p on p.supplier_id=s.id
left join (
  select supplier_id, sum(amount) as paid_total
  from public.supplier_payments
  group by supplier_id
) pay on pay.supplier_id=s.id;

grant select on public.supplier_balances to authenticated;
grant select,insert,update on public.suppliers to authenticated;
grant select,insert on public.supplier_payments to authenticated;

-- New purchase RPC that links a purchase to a supplier while preserving the
-- existing receive_purchase behavior and supplier-name compatibility.
create or replace function public.receive_purchase_v2(
  p_supplier_id bigint,
  p_supplier text,
  p_invoice_no text,
  p_purchase_date date,
  p_received_by uuid,
  p_total numeric,
  p_items jsonb
)
returns public.purchases
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.purchases;
  v_item jsonb;
  v_type text;
  v_product_id bigint;
  v_product public.products;
  v_qty integer;
  v_purchase_no text;
  v_phone_id bigint;
  v_supplier_name text;
begin
  if p_supplier_id is not null then
    select name into v_supplier_name from public.suppliers where id=p_supplier_id;
    if v_supplier_name is null then raise exception 'Supplier % was not found', p_supplier_id; end if;
  else
    v_supplier_name := nullif(trim(coalesce(p_supplier,'')),'');
  end if;

  v_purchase_no := 'PUR-' || to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
  insert into public.purchases(purchase_no,supplier,supplier_id,invoice_no,purchase_date,received_by,total)
  values(v_purchase_no,v_supplier_name,p_supplier_id,nullif(trim(coalesce(p_invoice_no,'')),''),coalesce(p_purchase_date,current_date),p_received_by,coalesce(p_total,0))
  returning * into v_purchase;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_type := coalesce(v_item->>'type','');
    if v_type='accessory' then
      v_product_id := nullif(v_item->>'product_id','')::bigint;
      v_qty := greatest(1,coalesce((v_item->>'quantity')::integer,1));
      select * into v_product from public.products where id=v_product_id for update;
      if not found then raise exception 'Product % was not found',v_product_id; end if;
      insert into public.purchase_items(purchase_id,item_type,product_id,product_name,quantity,unit_cost)
      values(v_purchase.id,'accessory',v_product.id,v_product.name,v_qty,coalesce((v_item->>'unit_cost')::numeric,0));
      update public.products set stock=stock+v_qty,cost=coalesce((v_item->>'unit_cost')::numeric,cost) where id=v_product.id;
    elsif v_type='phone' then
      if nullif(trim(v_item->>'imei_1'),'') is null then raise exception 'Phone IMEI 1 is required'; end if;
      if nullif(trim(v_item->>'brand'),'') is null or nullif(trim(v_item->>'model'),'') is null then raise exception 'Phone brand and model are required'; end if;
      insert into public.phone_units(brand,model,storage,ram,color,condition,imei_1,imei_2,cost,selling_price,supplier,purchase_date,warranty,status)
      values(trim(v_item->>'brand'),trim(v_item->>'model'),nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),coalesce((v_item->>'cost')::numeric,0),coalesce((v_item->>'selling_price')::numeric,0),v_supplier_name,coalesce(p_purchase_date,current_date),nullif(trim(v_item->>'warranty'),''),'In Stock') returning id into v_phone_id;
      insert into public.purchase_items(purchase_id,item_type,product_name,quantity,unit_cost,imei_1,imei_2,brand,model,storage,ram,color,condition,selling_price,warranty)
      values(v_purchase.id,'phone',trim(v_item->>'brand')||' '||trim(v_item->>'model'),1,coalesce((v_item->>'cost')::numeric,0),trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),trim(v_item->>'brand'),trim(v_item->>'model'),nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),coalesce((v_item->>'selling_price')::numeric,0),nullif(trim(v_item->>'warranty'),''));
    else raise exception 'Unknown purchase item type: %',v_type; end if;
  end loop;
  return v_purchase;
end;
$$;

grant execute on function public.receive_purchase_v2(bigint,text,text,date,uuid,numeric,jsonb) to authenticated;

-- v2.5: receive a purchase and optionally record the supplier payment made immediately.
create or replace function public.receive_purchase_v3(
  p_supplier_id bigint,
  p_invoice_no text,
  p_purchase_date date,
  p_received_by uuid,
  p_total numeric,
  p_initial_payment numeric,
  p_payment_method text,
  p_payment_reference text,
  p_items jsonb
)
returns public.purchases
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.purchases;
  v_item jsonb;
  v_type text;
  v_product_id bigint;
  v_product public.products;
  v_qty integer;
  v_purchase_no text;
  v_phone_id bigint;
  v_supplier_name text;
  v_paid numeric := greatest(coalesce(p_initial_payment,0),0);
begin
  select name into v_supplier_name from public.suppliers where id=p_supplier_id and active=true;
  if v_supplier_name is null then raise exception 'Active supplier was not found'; end if;
  if coalesce(p_total,0) < 0 then raise exception 'Purchase total cannot be negative'; end if;
  if v_paid > coalesce(p_total,0) then raise exception 'Initial supplier payment cannot exceed the purchase total'; end if;
  if v_paid > 0 and coalesce(nullif(trim(p_payment_method),''),'Cash') <> 'Cash' and nullif(trim(p_payment_reference),'') is null then
    raise exception 'Payment reference is required for electronic supplier payments';
  end if;

  v_purchase_no := 'PUR-' || to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
  insert into public.purchases(purchase_no,supplier,supplier_id,invoice_no,purchase_date,received_by,total)
  values(v_purchase_no,v_supplier_name,p_supplier_id,nullif(trim(coalesce(p_invoice_no,'')),''),coalesce(p_purchase_date,current_date),p_received_by,coalesce(p_total,0))
  returning * into v_purchase;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_type := coalesce(v_item->>'type','');
    if v_type='accessory' then
      v_product_id := nullif(v_item->>'product_id','')::bigint;
      v_qty := greatest(1,coalesce((v_item->>'quantity')::integer,1));
      select * into v_product from public.products where id=v_product_id for update;
      if not found then raise exception 'Product % was not found',v_product_id; end if;
      insert into public.purchase_items(purchase_id,item_type,product_id,product_name,quantity,unit_cost)
      values(v_purchase.id,'accessory',v_product.id,v_product.name,v_qty,coalesce((v_item->>'unit_cost')::numeric,0));
      update public.products set stock=stock+v_qty,cost=coalesce((v_item->>'unit_cost')::numeric,cost) where id=v_product.id;
    elsif v_type='phone' then
      if nullif(trim(v_item->>'imei_1'),'') is null then raise exception 'Phone IMEI 1 is required'; end if;
      if nullif(trim(v_item->>'brand'),'') is null or nullif(trim(v_item->>'model'),'') is null then raise exception 'Phone brand and model are required'; end if;
      insert into public.phone_units(brand,model,storage,ram,color,condition,imei_1,imei_2,cost,selling_price,supplier,purchase_date,warranty,status)
      values(trim(v_item->>'brand'),trim(v_item->>'model'),nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),coalesce((v_item->>'cost')::numeric,0),coalesce((v_item->>'selling_price')::numeric,0),v_supplier_name,coalesce(p_purchase_date,current_date),nullif(trim(v_item->>'warranty'),''),'In Stock') returning id into v_phone_id;
      insert into public.purchase_items(purchase_id,item_type,product_name,quantity,unit_cost,imei_1,imei_2,brand,model,storage,ram,color,condition,selling_price,warranty)
      values(v_purchase.id,'phone',trim(v_item->>'brand')||' '||trim(v_item->>'model'),1,coalesce((v_item->>'cost')::numeric,0),trim(v_item->>'imei_1'),nullif(trim(v_item->>'imei_2'),''),trim(v_item->>'brand'),trim(v_item->>'model'),nullif(trim(v_item->>'storage'),''),nullif(trim(v_item->>'ram'),''),nullif(trim(v_item->>'color'),''),coalesce(nullif(v_item->>'condition',''),'New'),coalesce((v_item->>'selling_price')::numeric,0),nullif(trim(v_item->>'warranty'),''));
    else raise exception 'Unknown purchase item type: %',v_type; end if;
  end loop;

  if v_paid > 0 then
    insert into public.supplier_payments(supplier_id,amount,payment_method,reference,paid_by)
    values(p_supplier_id,v_paid,coalesce(nullif(trim(p_payment_method),''),'Cash'),nullif(trim(p_payment_reference),''),p_received_by);
  end if;
  return v_purchase;
end;
$$;

grant execute on function public.receive_purchase_v3(bigint,text,date,uuid,numeric,numeric,text,text,jsonb) to authenticated;
